services:
  postgres:
    image: postgres:16-alpine
    container_name: lumastay-postgres
    environment:
      POSTGRES_DB: lumastay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - lumastay_pg:/var/lib/postgresql/data

volumes:
  lumastay_pg: